### ISSUE TITLE
(0.1.1) Chickens are all hungry but don't go eat.

### ISSUE THREAD

**Issue by Geethebluesky** [sbtoonz/chickenboo#1]
This is with version 0.1.1.

I have 5 chickens in a small pen. Two wild ones that were tamed, three chicks that grew up.

All of them have been hungry for a long time, but none of them are eating anymore; they're not even moving, even if I set them to "Follow". There's a stack of blueberries 1m next to them.

I think the pen might be too small to let them breed, but shouldn't they be eating and moving around anyway at least?

**Comment by mikeloeven** [comment]
I can confirm this sometimes their brain just breaks they will wonder randomly but not eat or switch to follow mode

**Comment by MysticDaedra** [comment]
Using version 2.0.8, this issue still persists. Any chance of a fix?

**Comment by mikeloeven** [comment]
Just wanted to check something I may have found a mod conflict causing this issue Does anyone else here also use the Mount Up mod ? for me disabling this resolved the issue something to look into

**Comment by lightsourced** [comment]
I have this issue right now, not using Mount Up. They are in a pen, and I have raspberries and dandelions on the ground they are hungry and not eating. Using primarily the Journey to Valhalla modpack.

**Comment by lightsourced** [comment]
I found that the array for tamable foods in the config file was empty by default. When I added Dandelion, Raspberry, and Carrot they started eating and became tame!
