### ISSUE TITLE
unable to cook the eggs

### ISSUE THREAD

**Issue by norby007** [sbtoonz/chickenboo#5]
I was finally able to get the raw eggs in the new update but unable to cook them. Even with a fresh install with nothing else loaded except the prerequisites. The recipe does not show up on any cooking station.

**Comment by ThePrussianMink** [comment]
Same here.

**Comment by DangerTimsen** [comment]
Same for me - no recipes for eggs. Thats sad - this mods is so cool :(

**Comment by norby007** [comment]
I use the tamable mod and feed the eggs to the necks. Unfortunately the chicken is useless as for some reason I cannot find an item ID for it.

**Comment by psionicalpha** [comment]
Same here.  I installed older and older versions until I finally ditched 2.0.0.   Once installing 0.1.5, I was able to get the recipes and cook both kinds of eggs.   I then upgraded back to 2.0.8, and I have the eggs in my inventory, but once again cannot craft them.

**Comment by psionicalpha** [comment]
Having tried all of the versions at this point, anything since the transition to version "2" is broken as far as cooking eggs.

**Comment by psionicalpha** [comment]
I updated to 2.0.9 today and can now cook eggs......in the workbench, not the cauldron.     that's okay though, i mix the leather scraps in with my eggs for flavoring, delicious!

**Comment by lightsourced** [comment]
I also see the egg recipes at the workbench... very weird. Wish they would only appear at the Cauldron!
